import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { getUsers } from "../../components/getData";

const index = () => {
    const [users, setUsers] = useState([]);

    useEffect(() => {
      const fetchUsers = async () => {
        const data = await getUsers();
        setUsers(data);
      };
      fetchUsers();
    }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {users.map((user) => (
            <a href={user.href} key={user.id} className={styles.card}>
              <h2>{user.name}</h2>
              <p>{user.description}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
};

export default index;
